- name: Container is running
  docker:
    image: "{{ consul_docker_image }}"
    name: consul
    net: host
    command: -advertise {{ ip }} {{ consul_extra }}
    state: started
  tags:
    - consul
