- include: consul.yml
  when: swarm_master

- name: Consul server is reachable from nodes
  wait_for:
    host: "{{ swarm_master_ip }}"
    port: 8301
  when: not swarm_master
  tags:
    - consul

- include: consul.yml
  when: not swarm_master
