- name: JQ is present
  apt:
    name: jq
    force: yes
  tags:
    - common

- name: Generate /tmp/hosts
  template:
    src: hosts.j2
    dest: /tmp/hosts
  tags:
    - common

- name: Read /tmp/hosts
  slurp: src=/tmp/hosts
  register: host_file
  tags:
    - common

- name: Append read content to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ host_file.content | b64decode }}"
  tags:
    - common

- name: Remove /tmp/hosts
  file: path=/tmp/hosts state=absent
  tags:
    - common
