- name: docker-py is present
  pip: name=docker-py state=present
  tags:
    - docker

- name: docker-compose is present
  pip: name=docker-compose state=present
  tags:
    - docker

- name: Modify DOCKER_OPTS
  lineinfile:
    dest: /etc/default/docker
    regexp: "^DOCKER_OPTS="
    insertafter: "^#DOCKER_OPTS="
    line: DOCKER_OPTS="{{ docker_opts }}"
  notify: restart docker
  tags:
    - docker

- meta: flush_handlers